default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

sqlite: &sqlite
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: juriba_storage_db_development
  username: postgres
  password: postgres
  host: localhost
  port: 5432

test:
  <<: *sqlite
  database: storage/test.sqlite3

production:
  <<: *default
  database: juriba_storage_db_production
  username: postgres
  password: <%= ENV["MYAPP_DATABASE_PASSWORD"] %>
  host: <%= ENV["MYAPP_DATABASE_HOST"] %>
  port: <%= ENV["MYAPP_DATABASE_PORT"] %>